
CREATE TABLE `PRODUCT` (
  `PRODUCT_ID` int PRIMARY KEY  NOT NULL,
  `NAME` varchar(20) DEFAULT NULL,
  `DESC` varchar(100) DEFAULT NULL,
  `PRICE` decimal(8,3) DEFAULT NULL
);

CREATE TABLE `EMPLOYEE` (
  `EMP_ID` int PRIMARY KEY,
  `NAME` varchar(20) DEFAULT NULL
);

CREATE TABLE MYDB.ID_GENERATOR (
 GEN_NAME varchar(60) PRIMARY KEY ,
 GEN_VAL int not null
)